# -*- coding: utf-8 -*-
"""NLP_Assignment_15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QsNFxtKge6mnEiC-AVWEsMPK7yWPX6C
"""

pip install tensorflow tensorflow-hub tensorflow-text scikit-learn numpy

sentences = [
    "Win money now",
    "Claim your prize",
    "Hello how are you",
    "Let's meet tomorrow",
    "Free lottery ticket",
    "Are you coming today"
]

labels = [1, 1, 0, 0, 1, 0]

import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

elmo = hub.load("https://tfhub.dev/google/elmo/3")
print("ELMo model loaded successfully")

import tensorflow as tf
import tensorflow_hub as hub

sentences = [
    "Win money now",
    "Claim your prize",
    "Hello how are you",
    "Let's meet tomorrow",
    "Free lottery ticket",
    "Are you coming today"
]

labels = [1, 1, 0, 0, 1, 0]

# Load ELMo model
elmo = hub.load("https://tfhub.dev/google/elmo/3")
print("ELMo model loaded successfully")

# Generate embeddings
elmo_embeddings = elmo.signatures['default'](tf.constant(sentences))['elmo']

print(elmo_embeddings.shape)

# Mean pooling across words
sentence_embeddings_elmo = tf.reduce_mean(elmo_embeddings, axis=1)

print(sentence_embeddings_elmo.shape)

# Mean pooling across words
sentence_embeddings_elmo = tf.reduce_mean(elmo_embeddings, axis=1)

print(sentence_embeddings_elmo.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    sentence_embeddings_elmo.numpy(),
    labels,
    test_size=0.33,
    random_state=42
)

from sklearn.naive_bayes import GaussianNB

nb_elmo = GaussianNB()
nb_elmo.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report

y_pred_elmo = nb_elmo.predict(X_test)

print("ELMo Accuracy:", accuracy_score(y_test, y_pred_elmo))
print(classification_report(y_test, y_pred_elmo))

import tensorflow_text as text

preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-512_A-8/2"

bert_preprocess = hub.KerasLayer(preprocess_url)
bert_encoder = hub.KerasLayer(encoder_url)

print("BERT model loaded successfully")

text_input = tf.constant(sentences)
preprocessed_text = bert_preprocess(text_input)

bert_outputs = bert_encoder(preprocessed_text)

# Use pooled output for sentence embedding
sentence_embeddings_bert = bert_outputs['pooled_output']

print(sentence_embeddings_bert.shape)

X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    sentence_embeddings_bert.numpy(),
    labels,
    test_size=0.33,
    random_state=42
)

nb_bert = GaussianNB()
nb_bert.fit(X_train_b, y_train_b)

y_pred_bert = nb_bert.predict(X_test_b)
print("BERT Accuracy:", accuracy_score(y_test_b, y_pred_bert))
print(classification_report(y_test_b, y_pred_bert))